Feature/app list search
HoloLabInc/HoloLensAppManager pull request #9
Opened 2019-10-24 06:28 UTC by cindychen0204

ボタンを追加しているレイアウトの書き方(InstallPage.xamlの107行から)はよくわからないです....
ビューア上はでかく表示していますが、Runtimeの時はいい感じの大きなになっています。

挙動の確認：
<a href="https://gyazo.com/a466e54e1c44d5a8e971785562a4341a"><img src="https://i.gyazo.com/a466e54e1c44d5a8e971785562a4341a.gif" alt="Image from Gyazo" width="944"/></a>

2019-10-24 07:41 UTC, cindychen0204 commented
AzureStorageUploader.cs　を削除
```
  public Task<List<AppInfo>> GetAppInfoListAsync(string searchKeywords = null)
        {
            throw new NotImplementedException();
        }
```

2019-10-24 08:38 UTC, cindychen0204 commented
InstallViewModel.csの
```
 var list = await uploader.GetAppInfoListAsync(keyword);
```
を利用して、データを選別する

2019-10-24 08:49 UTC, cindychen0204 commented
InstallViewModel.cs
```
        private ObservableCollection<AppInfoForInstall> searchedAppInfoList = new ObservableCollection<AppInfoForInstall>();
        public ObservableCollection<AppInfoForInstall> SearchedAppInfoList	        public ObservableCollection<AppInfoForInstall> AppInfoList
        {	        {
            get	            get
            {	            {
                return appInfoList;	                return appInfoList;
            }	            }
        }	        }

```
を作成

2019-10-24 08:50 UTC, cindychen0204 commented
InstallPage.xaml
```
            <ListView ItemsSource="{x:Bind Mode=OneWay, Path=ViewModel. SearchedAppInfoList}" x:Name="lv" Grid.Row="1" Margin="0,65,0,0" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" >
```

2019-10-24 08:56 UTC, cindychen0204 commented
編集要り 
````
<Grid
                Background="{ThemeResource SystemControlPageBackgroundChromeLowBrush}" Margin="0,0,0,650" HorizontalAlignment="Stretch" cu:Grid.Row="1">
                <TextBox x:Uid="SearchTextBox" Margin="10,10,634,-44" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" PlaceholderText="Search..." TextChanged ="TextBox_OnTextChanged"/>


            <ListView ItemsSource="{x:Bind Mode=OneWay, Path=ViewModel.AppInfoList}" x:Name="lv" Grid.Row="1" >	            </Grid>

```

2019-10-24 08:56 UTC, cindychen0204 commented
スペースで文字列を区切り（and）

2019-10-24 16:59 UTC, cindychen0204 commented
↑の指示によりリファクタリングしました。
検索機能に、スペースで区切り機能、大文字小文字対応する機能を追加しました

<a href="https://gyazo.com/da4ac5ec7c68ad20c1024b2bf02ed86a"><img src="https://i.gyazo.com/da4ac5ec7c68ad20c1024b2bf02ed86a.gif" alt="Image from Gyazo" width="922"/></a>

2019-10-25 01:21 UTC, tarukosu requested changes

2019-10-25 01:21 UTC, tarukosu commented on HoloLensAppManager/ViewModels/InstallViewModel.cs
> +        public async Task SearhWithKeyword(string keywordString)
```suggestion
        public async Task SearchWithQuery(string searchQuery)
```

2019-10-25 01:21 UTC, tarukosu commented on HoloLensAppManager/ViewModels/InstallViewModel.cs
> +            searchedAppInfoList.Clear();
SearchWithQuery の中身は以下にして、検索のアルゴリズムは MatchWithSearchQuery の中で書くのが良いかな

```
searchedAppInfoList = appInfoList.where(app => MatchWithSearchQuery(app, searchQuery);
```

2019-10-25 01:21 UTC, tarukosu commented on HoloLensAppManager/ViewModels/InstallViewModel.cs
> +        private bool IsContainStringArray(string aString, string[] stringArray)
変数名はもっとわかりやすい名前を付けよう

2019-10-25 01:21 UTC, tarukosu commented on HoloLensAppManager/Views/InstallPage.xaml.cs
> +        private void TextBox_OnTextChanged(object sender, TextChangedEventArgs e)
ViewModel のプロパティとのバインドを使えば、ここは不要になる

2019-10-25 04:00 UTC, cindychen0204 commented
これ動かなかったので、
```
        public async Task SearchWithQuery(string searchQuery)
        {
            searchedAppInfoListnew ObservableCollection<AppInfoForInstall>(AppInfoList.Where(app => MatchWithSearchQuery(app, searchQuery)));
        }
```

これにしました↓（なぜ！！！！！）

```
        public async Task SearchWithQuery(string searchQuery)
        {
            searchedAppInfoList.Clear();
            var newList = new ObservableCollection<AppInfoForInstall>(AppInfoList.Where(app => MatchWithSearchQuery(app, searchQuery)));
            foreach (var app in newList)
            {
                searchedAppInfoList.Add(app);
            }
        }
```

2019-10-25 04:06 UTC, tarukosu commented
@cindychen0204 
```
            searchedAppInfoList = new ObservableCollection<AppInfoForInstall>(AppInfoList.Where(app => MatchWithSearchQuery(app, searchQuery)));
```
これでいいと思うんだけど、なにがダメ？

https://stackoverflow.com/questions/38277807/linq-query-into-observablecollection

2019-10-25 04:08 UTC, cindychen0204 commented
私も行けると思っていました。しかし、実行の時はなにも更新されないです。

2019-10-25 04:09 UTC, tarukosu commented
そういうことね。

> 動かなかったので、

動かなかった理由を書くようにしましょう

2019-10-25 04:09 UTC, tarukosu commented
コンパイルが通らないのか、通ってるけどちゃんと動作してないのか、わからないので

2019-10-25 04:12 UTC, cindychen0204 commented
推論難しそうですね。
試しに、
 var newList = new ObservableCollection<AppInfoForInstall>(AppInfoList.Where(app => MatchWithSearchQuery(app, "1")));
で入れても、毎回タイプするときにDummyApplication１は出てくるはずですが、なにも更新されないです

<a href="https://gyazo.com/1cbe56366950befaa61b6329ab72db5e"><img src="https://i.gyazo.com/1cbe56366950befaa61b6329ab72db5e.gif" alt="Image from Gyazo" width="930"/></a>

2019-10-25 04:15 UTC, tarukosu commented
searchedAppInfoList 自体を変更しちゃったときに、それを view に通知する仕組みがないからダメなんだね。

```
 public async Task SearchWithQuery(string searchQuery)
        {
            var newAppList = AppInfoList.Where(app => MatchWithSearchQuery(app, searchQuery));
            searchedAppInfoList.Clear();
            foreach (var app in newAppList)
            {
                searchedAppInfoList.Add(app);
            }
        }
```

2019-10-25 04:15 UTC, cindychen0204 commented
ちなみに、アプリ実行時に一度実行されるUpdateApplicationList()に同じテスト文を入れるとうまく表示されます
 ```
 searchAppInfoList = new ObservableCollection<AppInfoForInstall>(AppInfoList.Where(app => MatchWithSearchQuery(app, "1")));
```

2019-10-25 04:16 UTC, cindychen0204 commented
searchedAppInfoList = new XXX は変更ではなかったということでしょうか？

2019-10-25 04:17 UTC, tarukosu commented
searchedAppInfoList = new XXX

だと、searchedAppInfoList の指す先がかわってて、

searchedAppInfoList.Clear()
searchedAppInfoList.Add()

だとsearchedAppInfoList の指す先は変わってないけど、指してる List の中身が変わってる

2019-10-25 04:20 UTC, cindychen0204 commented
納得しました。でしたら
```
 public async Task SearchWithQuery(string searchQuery)
        {
            var newAppList = AppInfoList.Where(app => MatchWithSearchQuery(app, searchQuery));
            searchedAppInfoList.Clear();
            foreach (var app in newAppList)
            {
                searchedAppInfoList.Add(app);
            }
        }
```
でいきます。

2019-10-25 04:22 UTC, cindychen0204 commented
バインドのところについて伺いしたいです！やはりどう考えても
```
        private void TextBox_OnTextChanged(object sender, TextChangedEventArgs e)
        {
            string keyword = ((TextBox) sender).Text;
            ViewModel.SearchWithQuery(keyword);
        }
```
は要ると思います...

2019-10-25 04:41 UTC, tarukosu commented
ユーザー名とかパスワードの入力部分を見れば、どうやったらいいかわかると思います

2019-10-25 04:55 UTC, cindychen0204 commented
プロパティのsetに任せると結構反応遅いので、元のままにしてもいいでしょうか？
```
        private string query;
        public string Query
        {
            get { return query; }
            set
            {
                this.Set(ref this.query, value);
                SearchWithQuery(query);
            }
        }
```

<a href="https://gyazo.com/c220a82a9283238950d10299d87f7ac2"><img src="https://i.gyazo.com/c220a82a9283238950d10299d87f7ac2.gif" alt="Image from Gyazo" width="928"/></a>

2019-10-25 05:02 UTC, tarukosu commented
@cindychen0204 
なぜ反応が遅いかわかる？

2019-10-25 05:11 UTC, cindychen0204 commented
プロパティの特徴ではないですか💦

2019-10-25 05:12 UTC, cindychen0204 commented
あ！わかりました
GetFocusも送らないと反応しないみたいです

2019-10-25 05:16 UTC, cindychen0204 commented
ちょっと違っていたかもしれません。とりあえずマウスは他のところにクリックしたらすぐ反応されます

2019-10-25 05:28 UTC, cindychen0204 commented
つまり、setは確実に文字列変更は一度とまるときだけ送信されるが、
textchangedは一文字でも変更された時点ではもう送信するようですね。

2019-10-25 06:53 UTC, tarukosu approved these changes

2019-10-25 06:53 UTC, merged